export const short = {
  military: [
    "Dépense efficace",
    "Vélocité spatiale",
    "Economie d'échelle",
    "Interrogatoire efficace",
    "Militarisation de l'empire",
    "Pilonnage",
    "Stratégie maîtrisée",
    "Vétéran",
    "Guerre éclair",
  ],
  trading: [
    "Économie développée",
    "Économie étendue",
    "Réseau financier",
    "Sécurisation boursière",
    "Économie sécuritaire",
    "Groupement financier",
    "Parrain",
    "Négociateur",
    "Roi Midas",
  ],
  technology: [
    "Progrès accéléré",
    "Rémanence",
    "Travail collaboratif",
    "Protection étendue",
    "Macro-technologie",
    "Sécurité planétaire",
    "Transmission du savoir",
    "Précurseur",
    "Science infuse",
  ],
  spying: [
    "Infiltration",
    "Paranoïa",
    "Chasseur de tête",
    "Inébranlable",
    "Efficacité prouvée",
    "Sécurité intérieure",
    "Communication quantique",
    "Espionnage massif",
    "Blackout",
  ],
  exploration: [
    "Maître explorateur",
    "Reconnaissance automatisée",
    "Analyse ciblée",
    "Armada",
    "Guerre irrégulière",
    "Expansion territoriale",
    "Planétologie avancée",
    "Astrophysique mathématisée",
    "Bouclier gravitationnelle",
  ],
  seclusion: [
    "Macro générateur",
    "Connaissance alien",
    "Navigation spatiale",
    "Vigilance",
    "Nano-ingénierie",
    "Puissance académique",
    "Collecteur d'énergie",
    "Cryptographie quantique",
    "Alliage composite",
  ],
  invasion: [
    "Déchainement",
    "Armure améliorée",
    "Conversion",
    "Manoeuvre furtive",
    "Service militaire",
    "Surveillance populaire",
    "Régiment de hussards",
    "Recherches secrètes",
    "Ouverture facile",
  ],
};

export const long = {
  military: [
    "Les vaisseaux militaires coûtent 20% moins cher en monnaie.",
    "Les vaisseaux militaires sont plus rapides de 5%.",
    "Les bases militaires coûtent 5% moins cher.",
    "La probabilité de découvrir la provenance d'un espion capturé est augmentée de 10%.",
    "La base militaire octroie un bonus plus important contre l'espionnage.",
    "La puissance de feu des défenses ennemies est réduite de 10%.",
    "La mise en place d'une stratégie requiert 10% moins d'énergie.",
    "L'expérience acquise par les commandants est augmentée de 50%.",
    "Aucune énergie n'est consommée lors du premier tour d'un combat.",
  ],
  trading: [
    "Le centre financier fournit une hausse de 5% en monnaie.",
    "La construction du centre financier coûte 5% moins cher.",
    "L'efficacité des centres financiers est augmentée de 10%.",
    "La sécurité est renforcée autour du centre financier (70% de chances en moins de se faire saboter).",
    "L'investissement dans le contre-espionnage est plus efficace de 15%.",
    "Les centres financiers présents dans le territoire de votre alliance se voit octroyer un bonus de 100 points.",
    "Une réduction de 20% est appliquée aux enchères dans le marché noir.",
    "Il est possible d'acheter de l'énergie et de la matière métallique au centre financier.",
    "Le bonus octroyé par un âge d'or est 200% plus élevé.",
  ],
  technology: [
    "Le temps de recherche de toutes les technologies est réduit de 10%.",
    "Augmentation de 15% sur la récupération des technologies élémentaires et avancées.",
    "Le coût des technologies est réduit de 5%.",
    "L'emplacement disponible au centre d'information sensible est augmenté de 4 places.",
    "Les technologies de vaisseaux mères sont 5% plus puissantes par niveau.",
    "Le temps est augmenté pour l'évacuation d'un artéfact ancien par l'ennemi.",
    "Vous obtenez la capacité d'augmenter la technologie d'autres empires.",
    "Le niveau de vos technologies équivaut au niveau supérieur.",
    "L'efficacité de chaque niveau technologique est augmenté de 15%.",
  ],
  spying: [
    "L'installation d'un réseau d'espionnage est 5% plus efficace.",
    "L'intelligence artificielle et la sécurité sont 5% plus efficaces dans le contre-espionnage.",
    "La probabilité de former un espion de haut niveau est augmentée.",
    "La probabilité qu'un de vos espions dévoile sa provenance est réduite de 30%.",
    "Le temps nécessaire à chaque action d'un espion est divisé par 2.",
    "Les espions en garnison dans le centre de renseignement octroie un bonus de contre-espionnage.",
    "La transmission d'informations est impossible à intercepter par l'ennemi.",
    "Le nombre d'espions disponibles est triplé.",
    "Un espion peut bloquer l'alerte durant les 30 premières minutes d'une attaque.",
  ],
  exploration: [
    "La vitesse des vaisseaux d'exploration est augmentée de 15%.",
    "La consommation d'énergie du vaisseau d'exploration est réduite de 15%.",
    "Le temps d'analyse d'une région est réduit de 20%.",
    "La capacité maximum de flottes en vol est augmentée de 10.",
    "Votre flotte gagne l'avantage du terrain sur certaines positions (géantes gazeuses, champs d'astéroïdes).",
    "Le nombre maximal de secteurs de production est augmenté de 20.",
    "L'exploitation de nouvelles ressources de luxe découvertes est temporairement multipliée par 10.",
    "L'exploration d'un trou de ver permet de connaître la date de son expiration.",
    "Il est possible de se positionner sur un trou noir et d'y utliser l'assistance gravitationnelle.",
  ],
  seclusion: [
    "Les vaisseaux mères ont la possiblité d'utiliser les trous de ver.",
    "Le coût des technologies xénomorphes est réduit de 5%.",
    "Les vaisseaux sont plus rapides de 5%.",
    "Un ennemi qui vous intercepte se voit infliger un malus.",
    "Les avantages des alliages sont 10% plus élevés.",
    "Le plafond d'expérience des commandants est relevé d'un niveau.",
    "Les vaisseaux consomment 30% moins d'énergie.",
    "La protection est accrue contre le piratage de données sur la cartographie.",
    "Un alliage métallique expérimental spécial est disponible.",
  ],
  invasion: [
    "Les invasions disposent d'une puissance de feu augmentée de 5%.",
    "La résistance de l'armure de vos soldats est augmentée de 5%.",
    "Lors d'une invasion, une partie des troupes ennemies est convertie (pallier 1 : 5%, pallier 2 : 10%, pallier 3 : 15%).",
    "Durant le premier tour d'une invasion, les dégâts reçus sont réduits de 10%.",
    "La formation d'infanterie requiert deux fois moins de population.",
    "Formation d'une milice dans la population réduisant la réussite des espions ennemis.",
    "Une nouvelle unité d'infanterie est disponible.",
    "Votre niveau de technologie d'armement xenomorphe équivaut au niveau supérieur.",
    "Permet de voler les technologies mises dans le centre d'information sensible en cas d'invasion réussie.",
  ],
};
